on:
  push:
    branches:
      - f37
    tags:
      - tag
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:37
      options: --privileged=true
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo dnf -y update
          sudo dnf -y install \
            rpmdevtools \
            mock fedpkg
      - name: Download Source
        run: |
          spectool -g *.spec
      - name: Safe Git
        run: |
          git config --global --add safe.directory /__w/serenelinux-icon/serenelinux-icon
      - name: Build RPMS
        run: |
          sudo fedpkg --release f37 mockbuild
      - name: Archive generated rpms
        uses: actions/upload-artifact@v2
        with:
          name: rpm-serenelinux-icon
          path: results_serenelinux-icon
      
      